from typing import Any

class Stealth:
    def __init__(self, **options: Any) -> None: ...
    async def apply_stealth_async(self, context: Any) -> None: ...
    def apply_stealth_sync(self, context: Any) -> None: ...
