from typing import Any

class PaddleOCR:
    def __init__(self, *, use_angle_cls: bool = ..., lang: str = ..., show_log: bool = ..., use_gpu: bool = ...) -> None: ...
    def ocr(self, img: str, *, cls: bool = ...) -> Any: ...
