from typing import Any, Awaitable, Optional

class APIConnectionError(Exception): ...
class Timeout(Exception): ...
class APIError(Exception): ...
class APIResponseValidationError(Exception): ...
class AuthenticationError(Exception): ...
class BadRequestError(Exception): ...
class NotFoundError(Exception): ...
class RateLimitError(Exception): ...
class ServiceUnavailableError(Exception): ...

suppress_debug_info: bool

def acompletion(
    model: str,
    messages: list[dict[str, Any]] = ...,
    *,
    timeout: Optional[float] = ...,
    temperature: Optional[float] = ...,
    max_tokens: Optional[int] = ...,
    response_format: Optional[type[Any] | dict[str, Any]] = ...,
    **kwargs: Any,
) -> Awaitable[Any]: ...
