from typing import Any, Iterator

class Page:
    def get_text(self) -> str: ...
    def get_pixmap(self, *, dpi: int = ...) -> "Pixmap": ...

class Pixmap:
    def tobytes(self) -> bytes: ...

class Document:
    needs_pass: bool
    def __iter__(self) -> Iterator[Page]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Document": ...
    def __exit__(self, *args: Any) -> None: ...

def open(path: str) -> Document: ...
